name: t
run-name: ${{ github.actor }} committed something random

on:
        push:
        workflow_dispatch:

jobs:
        check-code:
                runs-on: self-hosted
                steps:
                        - uses: actions/checkout@v3

                        - run: sudo docker compose up --detach --remove-orphans -S ${{ secrets.SUDO_PASSWORD }}
                          name: run the gawd damn proxi
